apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  REDIS_PASSWORD: ""
  VALID_API_KEYS: {{ .Values.validApiKeys | default "" | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.slackWebhookUrl | default "" | quote }}
  DD_API_KEY: {{ .Values.ddApiKey | default "" | quote }}
  GROUND_TRUTH_INGEST_TOKEN: {{ .Values.groundTruthIngestToken | default "" | quote }}
